### PR TITLE
fix shutdown logic

### LINKED ISSUE #24: Add shutdown logic
- [x] All connections should be shutdown
- [x] All checks should be gracefully terminated
- [x] Ctrl-c should work

### PR DESCRIPTION
**Pull request by rphillips**
Fixes #24

### CODE REVIEW

File: types/connection_stream.go [hunk 1]
```diff
@@ -56,6 +65,17 @@ func (cs *ConnectionStream) RegisterConnection(qry string, conn *Connection) {
 	cs.conns[qry] = conn
 }
 
+func (cs *ConnectionStream) Stop() {
+	for _, conn := range cs.conns {
+		conn.Close()
+	}
+	cs.stopCh <- struct{}{}
```
Comment (itzg) [inline types/connection_stream.go]: This `struct{}{}` looks kinda funny. If it can be anything, how about just a `1` or a string literal?

Comment (itzg) [inline types/connection_stream.go]: Nevermind, that actually makes the most "go" sense as a unspecified thing.

**Comment by rphillips** [comment]
cool. empty structs are a common golang channel notification mechanism.
